"""Add user_id, request_hash, status_code to idempotency_records

Revision ID: c045d5ef9e74
Revises: 474c88cb836a
Create Date: 2026-07-30 10:43:31.303417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c045d5ef9e74'
down_revision: Union[str, Sequence[str], None] = '474c88cb836a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_records', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('idempotency_records', sa.Column('request_hash', sa.String(), nullable=False))
    op.add_column('idempotency_records', sa.Column('status_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idempotency_records', 'status_code')
    op.drop_column('idempotency_records', 'request_hash')
    op.drop_column('idempotency_records', 'user_id')
    # ### end Alembic commands ###
